//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_VersionGather
    {
        public int Id { get; set; }
        public int ProvinceId { get; set; }
        public int ChannelId { get; set; }
        public int VersionId { get; set; }
        public int CopyrightType { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string ResourcesTypeName { get; set; }
        public Nullable<int> KeJian { get; set; }
        public Nullable<int> JiaoAn { get; set; }
        public Nullable<int> ShiTi { get; set; }
        public Nullable<int> XueAn { get; set; }
        public Nullable<int> SuCai { get; set; }
        public Nullable<int> ShiPin { get; set; }
        public Nullable<int> BeiKe { get; set; }
        public Nullable<int> AllCount { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
