//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Appraise
    {
        public int AppraiseID { get; set; }
        public int InfoID { get; set; }
        public Nullable<System.Guid> InfoGuID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string UserIP { get; set; }
        public string Title { get; set; }
        public int Star { get; set; }
        public string Content { get; set; }
        public Nullable<int> Platform { get; set; }
        public int Support { get; set; }
        public int NonSupport { get; set; }
        public int IsEssence { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> ChannelID { get; set; }
    }
}
