//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CID_ApprovalStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CID_ApprovalStep()
        {
            this.R_ApprovalStepOperator = new HashSet<R_ApprovalStepOperator>();
        }
    
        public int StepID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public string StepName { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual CID_ApprovalFlow CID_ApprovalFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ApprovalStepOperator> R_ApprovalStepOperator { get; set; }
    }
}
