//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CID_FlowStepRule
    {
        public int StepRuleID { get; set; }
        public Nullable<int> CurrStep { get; set; }
        public Nullable<int> NextStep { get; set; }
        public Nullable<int> StepNum { get; set; }
        public Nullable<int> StepOperID { get; set; }
        public Nullable<int> OperType { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
