//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_ApprovalInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cl_ApprovalInfo()
        {
            this.Cl_ApprovalOperInfo = new HashSet<Cl_ApprovalOperInfo>();
        }
    
        public int ApprovalID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> StepID { get; set; }
        public Nullable<int> IsCurrent { get; set; }
        public Nullable<int> OperStatus { get; set; }
        public Nullable<int> IsNew { get; set; }
        public Nullable<int> InfoID { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_ApprovalOperInfo> Cl_ApprovalOperInfo { get; set; }
    }
}
