//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_ApprovalOperInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cl_ApprovalOperInfo()
        {
            this.Cl_BackInfo = new HashSet<Cl_BackInfo>();
            this.Cl_ScoreInfo = new HashSet<Cl_ScoreInfo>();
        }
    
        public int AppInfoOperID { get; set; }
        public Nullable<int> ApprovalID { get; set; }
        public Nullable<int> StepOperID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
    
        public virtual Cl_ApprovalInfo Cl_ApprovalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_BackInfo> Cl_BackInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_ScoreInfo> Cl_ScoreInfo { get; set; }
    }
}
