//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_ArticleInnerLink
    {
        public int InnerLinkID { get; set; }
        public int ChannelID { get; set; }
        public string InnerLinkName { get; set; }
        public string InnerLinkURL { get; set; }
        public System.DateTime AddTime { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int UpdateUserID { get; set; }
        public string UpdateUserName { get; set; }
        public int IsDeleted { get; set; }
    }
}
