//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Admin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Purview { get; set; }
        public string Purview_Other { get; set; }
        public string arrClassMaster { get; set; }
        public string arrClassCheck { get; set; }
        public string arrClassInput { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public string AddUser { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastLogoutTime { get; set; }
        public Nullable<int> Pass { get; set; }
        public Nullable<int> WeekPass { get; set; }
        public Nullable<int> NoPass { get; set; }
        public Nullable<int> WeekNoPass { get; set; }
        public Nullable<int> Updates { get; set; }
        public Nullable<int> WeekUpdates { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<int> WeekLoginTimes { get; set; }
        public Nullable<int> Inform { get; set; }
        public Nullable<int> WeekInform { get; set; }
        public Nullable<int> Point0 { get; set; }
        public Nullable<int> OnTop { get; set; }
        public Nullable<int> Elite { get; set; }
        public Nullable<int> EMCard { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> Comment { get; set; }
        public Nullable<int> DownFiles { get; set; }
        public Nullable<int> WeekDownFiles { get; set; }
        public Nullable<int> AllPoint { get; set; }
        public Nullable<byte> IsDisabled { get; set; }
        public string OAUserID { get; set; }
        public string OAUserName { get; set; }
        public string OAPassport { get; set; }
        public Nullable<int> OAGroupID { get; set; }
        public string OAPurview { get; set; }
        public Nullable<int> UserIdentity { get; set; }
        public string OADepartment { get; set; }
    }
}
