//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_BackInfo
    {
        public int BackID { get; set; }
        public Nullable<int> AppInfoOperID { get; set; }
        public Nullable<int> BackTypeID { get; set; }
    
        public virtual CID_BackType CID_BackType { get; set; }
        public virtual Cl_ApprovalOperInfo Cl_ApprovalOperInfo { get; set; }
    }
}
