//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_BigExamCollect
    {
        public int BigExamCollectID { get; set; }
        public int CollectRelationID { get; set; }
        public Nullable<System.DateTime> ExamStartTime { get; set; }
        public Nullable<System.DateTime> ExamEndTime { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual R_CollectRelation R_CollectRelation { get; set; }
    }
}
