//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Channel
    {
        public int ChannelID { get; set; }
        public string ChannelName { get; set; }
        public string ChannelItemName { get; set; }
        public string ChannelItemUnit { get; set; }
        public string ChannelDir { get; set; }
        public string ReadMe { get; set; }
        public string LinkUrl { get; set; }
        public int OrderID { get; set; }
        public int ChannelType { get; set; }
        public int OpenType { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> IsDisabled { get; set; }
        public Nullable<int> IsCreateHtml { get; set; }
        public Nullable<int> CreatePathType { get; set; }
        public Nullable<int> CreateFileType { get; set; }
        public string CreateFileExt { get; set; }
        public Nullable<int> IsCreateList { get; set; }
        public Nullable<int> AutoCreateList { get; set; }
        public Nullable<int> StyleID { get; set; }
        public Nullable<int> CssID { get; set; }
        public string Logo { get; set; }
        public string Banner { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CusTom { get; set; }
        public string UpLoadSetting { get; set; }
        public string CountConfig { get; set; }
        public string OtherSetting { get; set; }
        public Nullable<int> IsRss { get; set; }
        public Nullable<int> IsWap { get; set; }
        public string DisableItem { get; set; }
        public Nullable<int> ServerItemID { get; set; }
    }
}
