//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_CollectOpinion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cl_CollectOpinion()
        {
            this.Cl_BigExamCollectOpinion = new HashSet<Cl_BigExamCollectOpinion>();
            this.Cl_CollectOpinionFile = new HashSet<Cl_CollectOpinionFile>();
            this.R_CollectRelation = new HashSet<R_CollectRelation>();
        }
    
        public int CollectOpinionID { get; set; }
        public int CollectTypeID { get; set; }
        public string CollectTitle { get; set; }
        public string Description { get; set; }
        public int InfoStatus { get; set; }
        public int ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string GradeID { get; set; }
        public string ChannelIDs { get; set; }
        public int AddUserID { get; set; }
        public string AddUserName { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateUserName { get; set; }
        public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_BigExamCollectOpinion> Cl_BigExamCollectOpinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_CollectOpinionFile> Cl_CollectOpinionFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CollectRelation> R_CollectRelation { get; set; }
    }
}
