//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Class_20170213
    {
        public int ClassID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public int ChannelID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentPath { get; set; }
        public string ClassDir { get; set; }
        public string ParentDir { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> RootID { get; set; }
        public Nullable<int> Child { get; set; }
        public string arrChildID { get; set; }
        public Nullable<int> PrevID { get; set; }
        public Nullable<int> NextID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ClassMaster { get; set; }
        public string Readme { get; set; }
        public string ClassPicUrl { get; set; }
        public Nullable<int> BrowsePurview { get; set; }
        public Nullable<int> AddPoint { get; set; }
        public bool IsElite { get; set; }
        public bool ShowOnTop { get; set; }
        public bool CommentIsChk { get; set; }
        public bool AddIsChk { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public Nullable<int> IsOuter { get; set; }
        public string LinkUrl { get; set; }
        public string CommentGroup { get; set; }
        public Nullable<int> DisabledAdd { get; set; }
        public string VipUser { get; set; }
        public Nullable<int> VersionID { get; set; }
        public string Version { get; set; }
        public Nullable<int> ChapterCount { get; set; }
        public string PageTitle { get; set; }
        public string PageKeywords { get; set; }
        public string PageDescription { get; set; }
        public string PageCrumbs { get; set; }
        public Nullable<int> IsDisplay { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
