//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_CollectOpinionRewardLog
    {
        public int LogID { get; set; }
        public int CollectOpinionTypeID { get; set; }
        public int CollectOpinionID { get; set; }
        public string Title { get; set; }
        public decimal RewardMoney { get; set; }
        public decimal RewardPoint { get; set; }
        public decimal RewardRMB { get; set; }
        public int RewardType { get; set; }
        public string ReceptUser { get; set; }
        public Nullable<int> ReceptUserID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public string AddUserName { get; set; }
    }
}
