//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Collect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cl_Collect()
        {
            this.R_CollectRelation = new HashSet<R_CollectRelation>();
        }
    
        public int SoftID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> SpecialID { get; set; }
        public string SoftName { get; set; }
        public string Prefixion { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> VersionID { get; set; }
        public string SoftVersion { get; set; }
        public string Author { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Editor { get; set; }
        public string Keyword { get; set; }
        public string OperatingSystem { get; set; }
        public Nullable<int> SoftTypeID { get; set; }
        public string SoftType { get; set; }
        public Nullable<int> SoftCateID { get; set; }
        public string SoftLanguage { get; set; }
        public string CopyrightType { get; set; }
        public string SoftIntro { get; set; }
        public Nullable<int> PresentPoint { get; set; }
        public Nullable<int> PresentMoney { get; set; }
        public Nullable<decimal> PresentRMB { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> CollectNums { get; set; }
        public Nullable<int> CollectPassNums { get; set; }
        public Nullable<int> IsCommonCollect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_CollectRelation> R_CollectRelation { get; set; }
    }
}
