//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_GroupPapers
    {
        public int PaperID { get; set; }
        public Nullable<int> PaperType { get; set; }
        public Nullable<int> GradeID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Author { get; set; }
        public int AuthorID { get; set; }
        public string Intro { get; set; }
        public string Content { get; set; }
        public Nullable<int> IncludePic { get; set; }
        public string PicUrl { get; set; }
        public int Hits { get; set; }
        public int DayHits { get; set; }
        public int WeekHits { get; set; }
        public int MonthHits { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Elite { get; set; }
        public bool Passed { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime LastHitTime { get; set; }
        public Nullable<int> GoodCount { get; set; }
        public Nullable<int> PoorCount { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> IsHot { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> PaperLable { get; set; }
        public Nullable<int> SchoolTypeID { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<System.DateTime> ShowTime { get; set; }
        public Nullable<int> IsNew { get; set; }
    }
}
