//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_GuestReply
    {
        public int ReplyID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string UserFace { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string UserEmail { get; set; }
        public string UserIP { get; set; }
        public string ReplyTitle { get; set; }
        public string ReplyEmote { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
