//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_GuestNew
    {
        public int GuestID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string UserEmail { get; set; }
        public string UserFace { get; set; }
        public string UserIP { get; set; }
        public string GuestTitle { get; set; }
        public string GuestEmote { get; set; }
        public string GuestContent { get; set; }
        public Nullable<System.DateTime> GuestTime { get; set; }
        public Nullable<int> IsReply { get; set; }
        public string ReplyUser { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public int Status { get; set; }
        public int Hidden { get; set; }
        public Nullable<int> ReplyCount { get; set; }
    }
}
