//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Guest
    {
        public int GuestId { get; set; }
        public Nullable<int> GuestMaxId { get; set; }
        public Nullable<int> GuestType { get; set; }
        public string GuestName { get; set; }
        public string GuestSex { get; set; }
        public string GuestOicq { get; set; }
        public string GuestMsn { get; set; }
        public string GuestIcq { get; set; }
        public string GuestEmail { get; set; }
        public string GuestHomepage { get; set; }
        public string GuestImages { get; set; }
        public string GuestFace { get; set; }
        public string GuestIP { get; set; }
        public string GuestTitle { get; set; }
        public string GuestContent { get; set; }
        public Nullable<System.DateTime> GuestDatetime { get; set; }
        public string GuestReply { get; set; }
        public string GuestReplyAdmin { get; set; }
        public Nullable<System.DateTime> GuestReplyDatetime { get; set; }
        public bool GuestIsPassed { get; set; }
        public bool GuestIsPrivate { get; set; }
    }
}
