//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Inform
    {
        public int ID { get; set; }
        public string ChannelID { get; set; }
        public Nullable<int> InfoID { get; set; }
        public string Title { get; set; }
        public string InfoUrl { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Whys { get; set; }
        public string ReMark { get; set; }
        public string AdminName { get; set; }
        public string AdminReply { get; set; }
        public Nullable<System.DateTime> AdminTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
