//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Js
    {
        public int ID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string JsName { get; set; }
        public string JsReadme { get; set; }
        public Nullable<int> JsType { get; set; }
        public string JsFileName { get; set; }
        public string Config { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> IsDynamic { get; set; }
        public Nullable<int> RefreshTimes { get; set; }
    }
}
