//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_MainVersion
    {
        public int MainVersionID { get; set; }
        public int ClassID { get; set; }
        public string ParentPath { get; set; }
        public int ChannelID { get; set; }
        public int VersionID { get; set; }
    }
}
