//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_OrderItem
    {
        public int ItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> MemberPrice { get; set; }
        public Nullable<decimal> TruePrice { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<int> ServiceTerm { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PresentExp { get; set; }
    }
}
