//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Order
    {
        public int OrderID { get; set; }
        public string OrderNum { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string ConSignee { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> DeliverType { get; set; }
        public bool NeedInvoice { get; set; }
        public string InvoiceHead { get; set; }
        public string Remark { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<decimal> TaxCharge { get; set; }
        public Nullable<decimal> DeliverCharge { get; set; }
        public Nullable<decimal> MoneyReceipt { get; set; }
        public Nullable<decimal> MoneySum { get; set; }
        public Nullable<decimal> MoneyTotal { get; set; }
        public Nullable<int> PresentExp { get; set; }
        public Nullable<int> Status { get; set; }
        public bool Invoiced { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
