//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Photo
    {
        public int PhotoID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string ChannelDir { get; set; }
        public int ClassID { get; set; }
        public string SpecialID { get; set; }
        public string PhotoName { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> FontType { get; set; }
        public string Prefixion { get; set; }
        public string Author { get; set; }
        public string AuthorEmail { get; set; }
        public string AuthorHomepage { get; set; }
        public string Editor { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> DayHits { get; set; }
        public Nullable<int> WeekHits { get; set; }
        public Nullable<int> MonthHits { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string PhotoPicUrl { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<int> PhotoSize { get; set; }
        public bool OnTop { get; set; }
        public bool Hot { get; set; }
        public bool Elite { get; set; }
        public bool Passed { get; set; }
        public string PhotoIntro { get; set; }
        public string PhotoLevel { get; set; }
        public Nullable<int> PhotoPoint { get; set; }
        public Nullable<int> PhotoMoney { get; set; }
        public bool Deleted { get; set; }
        public bool IsDownLoad { get; set; }
        public Nullable<int> DownLoadNum { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<System.DateTime> LastHitTime { get; set; }
        public bool IsHtml { get; set; }
        public string HtmlFileUrl { get; set; }
        public string UploadFiles { get; set; }
        public Nullable<bool> NoPass { get; set; }
        public Nullable<int> NoPassNum { get; set; }
        public string NoPasstxt { get; set; }
        public string Censor { get; set; }
        public Nullable<System.DateTime> CensorTime { get; set; }
        public Nullable<int> BackPoint { get; set; }
        public Nullable<int> BackPointRate { get; set; }
        public Nullable<int> BackMoney { get; set; }
        public Nullable<int> BackMoneyRate { get; set; }
        public Nullable<int> IsAward { get; set; }
    }
}
