//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_PassIP
    {
        public int ID { get; set; }
        public string PassIP { get; set; }
        public string PassName { get; set; }
        public Nullable<int> Purview { get; set; }
        public string arrClassID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<int> UseDayNum { get; set; }
        public Nullable<long> MaxFiles { get; set; }
        public Nullable<long> DownFiles { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<bool> IsSpeed { get; set; }
    }
}
