//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_ProductRecycleBin
    {
        public int ProductID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string ChannelDir { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string SpecialID { get; set; }
        public string ProductName { get; set; }
        public string Prefixion { get; set; }
        public string ProductSn { get; set; }
        public string Producer { get; set; }
        public string Trademark { get; set; }
        public string ProductModel { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public string ProductIntro { get; set; }
        public string ProductExplain { get; set; }
        public Nullable<decimal> MarketPrice { get; set; }
        public Nullable<decimal> MemberPrice { get; set; }
        public Nullable<decimal> TruePrice { get; set; }
        public Nullable<double> Discount { get; set; }
        public bool IncludeTax { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<int> ProductPoint { get; set; }
        public Nullable<int> StockNum { get; set; }
        public string BuyLevel { get; set; }
        public Nullable<int> PresentExp { get; set; }
        public string ProductPicUrl { get; set; }
        public bool IsSoft { get; set; }
        public string DownloadUrl { get; set; }
        public bool OnTop { get; set; }
        public bool Hot { get; set; }
        public bool Elite { get; set; }
        public bool Passed { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> DayHits { get; set; }
        public Nullable<int> WeekHits { get; set; }
        public Nullable<int> MonthHits { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> BuyTimes { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool NoOver { get; set; }
        public string Keyword { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public bool IsHtml { get; set; }
        public string HtmlFileUrl { get; set; }
        public Nullable<System.DateTime> LastHitTime { get; set; }
        public Nullable<bool> NoPass { get; set; }
        public Nullable<int> NoPassNum { get; set; }
        public string NoPasstxt { get; set; }
        public string Censor { get; set; }
        public Nullable<System.DateTime> CensorTime { get; set; }
        public Nullable<int> BackPoint { get; set; }
        public Nullable<int> BackPointRate { get; set; }
        public Nullable<int> BackMoney { get; set; }
        public Nullable<int> BackMoneyRate { get; set; }
        public Nullable<int> IsAward { get; set; }
    }
}
