//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string PaymentNum { get; set; }
        public Nullable<int> eBankID { get; set; }
        public string PayMobile { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public Nullable<decimal> TrueMoney { get; set; }
        public Nullable<decimal> GetMoney { get; set; }
        public Nullable<decimal> GetPoint { get; set; }
        public Nullable<decimal> GetAdvPoint { get; set; }
        public Nullable<decimal> GetRMBincome { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string eBankInfo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsLoveHeart { get; set; }
        public string UserReName { get; set; }
        public string Address { get; set; }
        public string Bless { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> PayWay { get; set; }
    }
}
