//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_QuickPayCard
    {
        public int CardID { get; set; }
        public int UserID { get; set; }
        public string CardBank { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string CardExp { get; set; }
        public string CardCvv2 { get; set; }
        public string CardName { get; set; }
        public string CardIDType { get; set; }
        public string CardIDNo { get; set; }
        public string CardPhone { get; set; }
    }
}
