//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Researcher
    {
        public int UserID { get; set; }
        public int UserState { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> DimissionTime { get; set; }
        public Nullable<int> EditUserID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> SchoolType { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ChannleID { get; set; }
        public Nullable<int> ClassID { get; set; }
    }
}
