//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cl_Role()
        {
            this.R_RoleSoftContentManage = new HashSet<R_RoleSoftContentManage>();
            this.R_UserRole = new HashSet<R_UserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> IdentityID { get; set; }
        public Nullable<int> SoftAction { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_RoleSoftContentManage> R_RoleSoftContentManage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_UserRole> R_UserRole { get; set; }
    }
}
