//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_SoftRecycleBin
    {
        public int SoftID { get; set; }
        public System.Guid InfoGuid { get; set; }
        public int CollectID { get; set; }
        public int ChannelID { get; set; }
        public int ClassID { get; set; }
        public int ChapterID { get; set; }
        public int NodeID { get; set; }
        public Nullable<int> WholeID { get; set; }
        public int SpecialID { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> GradeID { get; set; }
        public string Prefixion { get; set; }
        public string SoftName { get; set; }
        public string FontColor { get; set; }
        public int FontType { get; set; }
        public Nullable<int> VersionID { get; set; }
        public string SoftVersion { get; set; }
        public string Keyword { get; set; }
        public int AreaID { get; set; }
        public string Author { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> SoftTypeID { get; set; }
        public string SoftType { get; set; }
        public Nullable<int> SoftCateID { get; set; }
        public string SoftLanguage { get; set; }
        public string CopyrightType { get; set; }
        public int SoftSize { get; set; }
        public string SoftLevel { get; set; }
        public decimal SoftPoint { get; set; }
        public decimal SoftMoney { get; set; }
        public int Stars { get; set; }
        public int Hits { get; set; }
        public int DayHits { get; set; }
        public int WeekHits { get; set; }
        public int MonthHits { get; set; }
        public bool OnTop { get; set; }
        public bool Elite { get; set; }
        public bool Passed { get; set; }
        public int IsAward { get; set; }
        public int IsSchool { get; set; }
        public Nullable<int> IsSupply { get; set; }
        public Nullable<int> IsBoutique { get; set; }
        public Nullable<int> IncludePic { get; set; }
        public string PicUrl { get; set; }
        public string Intro { get; set; }
        public string FileAddress { get; set; }
        public int BackPoint { get; set; }
        public int BackPointRate { get; set; }
        public int BackMoney { get; set; }
        public int BackMoneyRate { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Censor { get; set; }
        public Nullable<System.DateTime> CensorTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime LastHitTime { get; set; }
        public Nullable<int> GoodCount { get; set; }
        public Nullable<int> PoorCount { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IsAnalyze { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> IsRecommend { get; set; }
        public Nullable<int> IsCustom { get; set; }
        public Nullable<int> AppState { get; set; }
        public Nullable<int> ServiceSource { get; set; }
        public Nullable<int> IsSelfCommand { get; set; }
        public Nullable<int> CollectType { get; set; }
        public Nullable<int> SoftFormat { get; set; }
        public Nullable<int> IsAnswer { get; set; }
        public string ChildSoftName { get; set; }
        public Nullable<int> IsOptimization { get; set; }
    }
}
