//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Special
    {
        public int SpecialID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string SpecialName { get; set; }
        public string SpecialMaster { get; set; }
        public string ReadMe { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> RootID { get; set; }
        public Nullable<int> Child { get; set; }
        public string arrChildID { get; set; }
        public Nullable<int> PrevID { get; set; }
        public Nullable<int> NextID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
