//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_SearchXmlData
    {
        public int SearchXmlDataID { get; set; }
        public int Year { get; set; }
        public string AreaName { get; set; }
        public string Paper { get; set; }
        public int AreaID { get; set; }
        public string Subject { get; set; }
        public int SubjectID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string PaperUrl { get; set; }
        public string JieXiLink { get; set; }
    }
}
