//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Setup
    {
        public int ID { get; set; }
        public string Web_Info { get; set; }
        public string Web_Setting { get; set; }
        public Nullable<int> Web_StyleID { get; set; }
        public Nullable<int> Web_CssID { get; set; }
        public string Web_Version { get; set; }
        public string Web_Pack { get; set; }
        public string Badwords { get; set; }
        public string rBadword { get; set; }
        public string LockIP { get; set; }
        public string Regword { get; set; }
        public string UpLoad_Setting { get; set; }
        public string Product_Setting { get; set; }
        public string SqlInword { get; set; }
        public string NoChkSqlInFiles { get; set; }
        public string Web_Css { get; set; }
    }
}
