//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_UpFileLog
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public string UserIP { get; set; }
        public string UpFileName { get; set; }
        public string SaveFileName { get; set; }
        public Nullable<System.DateTime> UpFileTime { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> InfoID { get; set; }
        public Nullable<int> IsUse { get; set; }
    }
}
