//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_UserGroupLog
    {
        public int LogID { get; set; }
        public Nullable<int> CurrUserID { get; set; }
        public string CurrUserName { get; set; }
        public Nullable<int> CurrGroupID { get; set; }
        public Nullable<int> OperUserID { get; set; }
        public string OperUserName { get; set; }
        public Nullable<System.DateTime> OperTime { get; set; }
        public Nullable<int> ChangeType { get; set; }
    }
}
