//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_UserCz
    {
        public int ID { get; set; }
        public string CzNum { get; set; }
        public string Pass { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> DayNum { get; set; }
        public Nullable<int> IsUser { get; set; }
        public Nullable<int> CzType { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public string CzUserName { get; set; }
        public string EMUser { get; set; }
        public string EMAdmin { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> IsLock { get; set; }
    }
}
