//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_UserGroup
    {
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string GroupIntro { get; set; }
        public string GroupImg { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<int> GroupPoint { get; set; }
        public Nullable<int> ValidDays { get; set; }
        public Nullable<int> LoginPoint { get; set; }
        public string Purview { get; set; }
        public string Purview_Other { get; set; }
        public string arrClassView { get; set; }
        public string arrClassInput { get; set; }
        public string arrClassCheck { get; set; }
        public string arrClassMaster { get; set; }
    }
}
