//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cl_Vote
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Nums { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> totalNums { get; set; }
        public Nullable<int> IsNew { get; set; }
        public System.DateTime VoteTime { get; set; }
        public Nullable<int> ChannelID { get; set; }
    }
}
