//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Article_Bak_Sync
    {
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public int SpecialID { get; set; }
        public int FeatureID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Prefixion { get; set; }
        public string Title { get; set; }
        public string FontColor { get; set; }
        public int FontType { get; set; }
        public string TitleIntact { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Author { get; set; }
        public int AuthorID { get; set; }
        public string CopyFrom { get; set; }
        public string ArticleLevel { get; set; }
        public decimal ArticlePoint { get; set; }
        public decimal ArticleMoney { get; set; }
        public int Stars { get; set; }
        public Nullable<int> Hits { get; set; }
        public Nullable<int> DayHits { get; set; }
        public Nullable<int> WeekHits { get; set; }
        public Nullable<int> MonthHits { get; set; }
        public int OnTop { get; set; }
        public Nullable<int> Elite { get; set; }
        public int Passed { get; set; }
        public int IncludePic { get; set; }
        public string PicUrl { get; set; }
        public string Intro { get; set; }
        public string Content { get; set; }
        public int IsLink { get; set; }
        public string HtmlFileUrl { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Censor { get; set; }
        public Nullable<System.DateTime> CensorTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public System.DateTime LastHitTime { get; set; }
        public int GoodCount { get; set; }
        public int PoorCount { get; set; }
        public Nullable<System.Guid> InfoGuid { get; set; }
        public int GradeID { get; set; }
        public int ArticleYear { get; set; }
        public int SubjectID { get; set; }
    }
}
