//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_postings
    {
        public int id { get; set; }
        public string autor { get; set; }
        public string title { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> replies { get; set; }
        public string datum { get; set; }
        public string message { get; set; }
        public string updated { get; set; }
        public Nullable<int> connected { get; set; }
        public string datum_updated { get; set; }
    }
}
