//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CollectRelation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_CollectRelation()
        {
            this.Cl_BigExamCollect = new HashSet<Cl_BigExamCollect>();
        }
    
        public int CollectRelationID { get; set; }
        public int CollectOpinionID { get; set; }
        public int CollectID { get; set; }
        public int CollectTypeID { get; set; }
    
        public virtual CID_CollectType CID_CollectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cl_BigExamCollect> Cl_BigExamCollect { get; set; }
        public virtual Cl_Collect Cl_Collect { get; set; }
        public virtual Cl_CollectOpinion Cl_CollectOpinion { get; set; }
    }
}
