//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XK_BaoMing
    {
        public int ID { get; set; }
        public string YanXiao { get; set; }
        public string ZhuanYe { get; set; }
        public string XueZhi { get; set; }
        public string TrueName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string IDCard { get; set; }
        public string MinZu { get; set; }
        public string JiGuan { get; set; }
        public string XueLi { get; set; }
        public string FinishSchool { get; set; }
        public Nullable<int> FinishYear { get; set; }
        public string MianMao { get; set; }
        public string LinkAddress { get; set; }
        public Nullable<int> LinkZipCode { get; set; }
        public string LinkEmail { get; set; }
        public string LinkPhone { get; set; }
        public string LinkQQ { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
