//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XK_Chapter
    {
        public int ChapterID { get; set; }
        public string ChapterName { get; set; }
        public string ChapterIntro { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> NodeCount { get; set; }
    }
}
