//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XK_CDBuy
    {
        public int ID { get; set; }
        public string ReName { get; set; }
        public string Email { get; set; }
        public string AddRess { get; set; }
        public string ZipCode { get; set; }
        public string TelePhone { get; set; }
        public string MobilePhone { get; set; }
        public string RemitBank { get; set; }
        public Nullable<decimal> RemitMoney { get; set; }
        public string CDType { get; set; }
        public string UserType { get; set; }
        public int BuyNums { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
