//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XK_Question
    {
        public int ID { get; set; }
        public int SortID { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public int QUserID { get; set; }
        public string QUserName { get; set; }
        public System.DateTime QDateTime { get; set; }
        public string Answer { get; set; }
        public int AUserID { get; set; }
        public string AUserName { get; set; }
        public Nullable<System.DateTime> ADateTime { get; set; }
        public int Hits { get; set; }
        public int Helpful { get; set; }
        public int Helpless { get; set; }
        public byte isElite { get; set; }
        public byte isOntop { get; set; }
    }
}
