//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XK_Subject
    {
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public string SubjectEnglishName { get; set; }
        public int OrderID { get; set; }
        public byte IsDisabled { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
