//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZK_Paper
    {
        public int PaperID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Title { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Passed { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
