//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZZ_DEL_XK_School_Del
    {
        public int SchoolID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AreaName { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> SchoolLevel { get; set; }
        public string SchoolType { get; set; }
        public string SchoolPhone { get; set; }
        public string SchoolRector { get; set; }
        public string SchoolZipCode { get; set; }
        public string SchoolAddRess { get; set; }
        public string SchoolIntro { get; set; }
        public Nullable<int> SchoolStar { get; set; }
        public string LinkMan { get; set; }
        public string LinkMobile { get; set; }
        public string LinkPhone { get; set; }
        public string LinkEmail { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
