//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_02_22_Swagger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZZ_DEL_XK_SchoolArea_Del
    {
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> RootID { get; set; }
        public Nullable<int> Child { get; set; }
        public string arrChildID { get; set; }
        public Nullable<int> PrevID { get; set; }
        public Nullable<int> NextID { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
